function mover(x,y,mass,staticcondition,startxvel,startyvel,friction){
  this.x=x;
  this.y=y;
  this.yvel=startyvel;
  this.xvel=startxvel;
  this.yacc=0;
  this.xacc=0;
  this.mass=mass;
  this.isStatic=staticcondition;
  this.frictionlevel=friction;
  this.actualfriction=1-this.frictionlevel;
  // this.r=map(this.mass,0,3,0,5);
  this.r=20;
  this.color={r:random(map(this.mass,0,10,200,100),255),g:random(map(this.mass,0,10,200,100),255),b:random(map(this.mass,0,10,200,100),255)};
  this.update=function(){
    this.x+=this.xvel;
    this.y+=this.yvel;
    this.xvel+=this.xacc;
    this.yvel+=this.yacc;
    this.xvel*=this.actualfriction;
    this.yvel*=this.actualfriction;
    this.xacc*=0;
    this.yacc*=0;
    if(this.isStatic){
      this.xvel=0;
      this.yvel=0;
      this.xacc=0;
      this.yacc=0;
    }
  }
  this.applyForce=function(x,y){
    if(this.isStatic==false){
      this.xacc+=x/this.mass;
      this.yacc+=y/this.mass;
    }
  }
  this.show=function(){
    noFill();
    stroke(this.color.r,this.color.g,this.color.b);
    ellipse(this.x,this.y,this.r,this.r);
  }
}
